# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: '217 acorn'
    sourceFolder: '$(System.DefaultWorkingDirectory)/AcornAPI/bin/Release/netcoreapp2.2/'
    contents: '**'
    targetFolder: '/apis/acornapi'
    readyTimeout: '20000'

- task: SSH@0
  inputs:
    sshEndpoint: '217 acorn'
    runOptions: 'commands'
    commands: 'sudo systemctl restart acorn-api.service'
    readyTimeout: '20000'
