//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acorn.DAL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acorn.DAL.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account does not exist.
        /// </summary>
        internal static string AccNotExistString {
            get {
                return ResourceManager.GetString("AccNotExistString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Bot with this id already exists.
        /// </summary>
        internal static string BotAlreadyExistString {
            get {
                return ResourceManager.GetString("BotAlreadyExistString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot does not exist.
        /// </summary>
        internal static string BotNotExistString {
            get {
                return ResourceManager.GetString("BotNotExistString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config does not exist.
        /// </summary>
        internal static string ConfigNotExistString {
            get {
                return ResourceManager.GetString("ConfigNotExistString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreshAccount does not exist.
        /// </summary>
        internal static string FreshAccNotExistString {
            get {
                return ResourceManager.GetString("FreshAccNotExistString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log does not exist.
        /// </summary>
        internal static string LogNotExistString {
            get {
                return ResourceManager.GetString("LogNotExistString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No FreshAccount with requested region exists.
        /// </summary>
        internal static string NoFreshAccInRegionString {
            get {
                return ResourceManager.GetString("NoFreshAccInRegionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadyAccount does not exist.
        /// </summary>
        internal static string ReadyAccNotExistString {
            get {
                return ResourceManager.GetString("ReadyAccNotExistString", resourceCulture);
            }
        }
    }
}
