//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acorn.BL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acorn.BL.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account&apos;s validation failed.
        /// </summary>
        internal static string AccValidFailString {
            get {
                return ResourceManager.GetString("AccValidFailString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot with ID = {0} doesn&apos;t exist.
        /// </summary>
        internal static string BotNotExist {
            get {
                return ResourceManager.GetString("BotNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot&apos;s validation failed - make sure that BotId is between 1 and 999.
        /// </summary>
        internal static string BotValidFailString {
            get {
                return ResourceManager.GetString("BotValidFailString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config&apos;s validation failed.
        /// </summary>
        internal static string ConfigValidFailString {
            get {
                return ResourceManager.GetString("ConfigValidFailString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreshAccount&apos;s validation failed.
        /// </summary>
        internal static string FreshAccValidFailString {
            get {
                return ResourceManager.GetString("FreshAccValidFailString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log&apos;s validation failed.
        /// </summary>
        internal static string LogValidFailString {
            get {
                return ResourceManager.GetString("LogValidFailString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid length of password hash (64 bytes expected)..
        /// </summary>
        internal static string PassHashInvalidLengthString {
            get {
                return ResourceManager.GetString("PassHashInvalidLengthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid length of password salt (128 bytes expected)..
        /// </summary>
        internal static string PassSaltInvalidLengthString {
            get {
                return ResourceManager.GetString("PassSaltInvalidLengthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string PasswordReqString {
            get {
                return ResourceManager.GetString("PasswordReqString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadyAccount&apos;s validation failed.
        /// </summary>
        internal static string ReadyAccValidFail {
            get {
                return ResourceManager.GetString("ReadyAccValidFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username &quot;{0}&quot; is already taken.
        /// </summary>
        internal static string UsernameTakenString {
            get {
                return ResourceManager.GetString("UsernameTakenString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string UserNotFoundString {
            get {
                return ResourceManager.GetString("UserNotFoundString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty or whitespace only string.
        /// </summary>
        internal static string ValEmptyOrWhitespaceString {
            get {
                return ResourceManager.GetString("ValEmptyOrWhitespaceString", resourceCulture);
            }
        }
    }
}
